#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern void _bk_fs_reg(void);
extern void _bk_ms_reg(void);
extern void _cadyn_fs_reg(void);
extern void _cadyn_ms_reg(void);
extern void _cal12_ms_reg(void);
extern void _cal13_ms_reg(void);
extern void _caldyn_ms_reg(void);
extern void _can_fs_reg(void);
extern void _can_ms_reg(void);
extern void _caq_fs_reg(void);
extern void _caq_ms_reg(void);
extern void _car_fs_reg(void);
extern void _car_ms_reg(void);
extern void _cat32_ms_reg(void);
extern void _cat33_ms_reg(void);
extern void _concACh_ms_reg(void);
extern void _concDA_ms_reg(void);
extern void _Im_ms_reg(void);
extern void _kaf_fs_reg(void);
extern void _kaf_ms_reg(void);
extern void _kas_fs_reg(void);
extern void _kas_ms_reg(void);
extern void _kdr_fs_reg(void);
extern void _kdr_ms_reg(void);
extern void _kir_fs_reg(void);
extern void _kir_ms_reg(void);
extern void _naf_fs_reg(void);
extern void _naf_ms_reg(void);
extern void _par_ggap_reg(void);
extern void _sk_fs_reg(void);
extern void _sk_ms_reg(void);
extern void _tmgabaa_reg(void);
extern void _tmglut_M1RH_D1_reg(void);
extern void _tmglut_reg(void);
extern void _vecevent_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," ../../../renamed_mod_files//bk_fs.mod");
    fprintf(stderr," ../../../renamed_mod_files//bk_ms.mod");
    fprintf(stderr," ../../../renamed_mod_files//cadyn_fs.mod");
    fprintf(stderr," ../../../renamed_mod_files//cadyn_ms.mod");
    fprintf(stderr," ../../../renamed_mod_files//cal12_ms.mod");
    fprintf(stderr," ../../../renamed_mod_files//cal13_ms.mod");
    fprintf(stderr," ../../../renamed_mod_files//caldyn_ms.mod");
    fprintf(stderr," ../../../renamed_mod_files//can_fs.mod");
    fprintf(stderr," ../../../renamed_mod_files//can_ms.mod");
    fprintf(stderr," ../../../renamed_mod_files//caq_fs.mod");
    fprintf(stderr," ../../../renamed_mod_files//caq_ms.mod");
    fprintf(stderr," ../../../renamed_mod_files//car_fs.mod");
    fprintf(stderr," ../../../renamed_mod_files//car_ms.mod");
    fprintf(stderr," ../../../renamed_mod_files//cat32_ms.mod");
    fprintf(stderr," ../../../renamed_mod_files//cat33_ms.mod");
    fprintf(stderr," ../../../renamed_mod_files//concACh_ms.mod");
    fprintf(stderr," ../../../renamed_mod_files//concDA_ms.mod");
    fprintf(stderr," ../../../renamed_mod_files//Im_ms.mod");
    fprintf(stderr," ../../../renamed_mod_files//kaf_fs.mod");
    fprintf(stderr," ../../../renamed_mod_files//kaf_ms.mod");
    fprintf(stderr," ../../../renamed_mod_files//kas_fs.mod");
    fprintf(stderr," ../../../renamed_mod_files//kas_ms.mod");
    fprintf(stderr," ../../../renamed_mod_files//kdr_fs.mod");
    fprintf(stderr," ../../../renamed_mod_files//kdr_ms.mod");
    fprintf(stderr," ../../../renamed_mod_files//kir_fs.mod");
    fprintf(stderr," ../../../renamed_mod_files//kir_ms.mod");
    fprintf(stderr," ../../../renamed_mod_files//naf_fs.mod");
    fprintf(stderr," ../../../renamed_mod_files//naf_ms.mod");
    fprintf(stderr," ../../../renamed_mod_files//par_ggap.mod");
    fprintf(stderr," ../../../renamed_mod_files//sk_fs.mod");
    fprintf(stderr," ../../../renamed_mod_files//sk_ms.mod");
    fprintf(stderr," ../../../renamed_mod_files//tmgabaa.mod");
    fprintf(stderr," ../../../renamed_mod_files//tmglut_M1RH_D1.mod");
    fprintf(stderr," ../../../renamed_mod_files//tmglut.mod");
    fprintf(stderr," ../../../renamed_mod_files//vecevent.mod");
    fprintf(stderr, "\n");
  }
  _bk_fs_reg();
  _bk_ms_reg();
  _cadyn_fs_reg();
  _cadyn_ms_reg();
  _cal12_ms_reg();
  _cal13_ms_reg();
  _caldyn_ms_reg();
  _can_fs_reg();
  _can_ms_reg();
  _caq_fs_reg();
  _caq_ms_reg();
  _car_fs_reg();
  _car_ms_reg();
  _cat32_ms_reg();
  _cat33_ms_reg();
  _concACh_ms_reg();
  _concDA_ms_reg();
  _Im_ms_reg();
  _kaf_fs_reg();
  _kaf_ms_reg();
  _kas_fs_reg();
  _kas_ms_reg();
  _kdr_fs_reg();
  _kdr_ms_reg();
  _kir_fs_reg();
  _kir_ms_reg();
  _naf_fs_reg();
  _naf_ms_reg();
  _par_ggap_reg();
  _sk_fs_reg();
  _sk_ms_reg();
  _tmgabaa_reg();
  _tmglut_M1RH_D1_reg();
  _tmglut_reg();
  _vecevent_reg();
}
